### ISSUE TITLE
Specs Broken?

### ISSUE THREAD

**Issue by gaurish** [kenn/slavery#7]
Hello, 
Are the specs broken?

Please see below:

``` ruby
/Users/gaurish/.rvm/rubies/ruby-2.3.1/bin/ruby -I/Users/gaurish/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.5.4/lib:/Users/gaurish/.rvm/gems/ruby-2.3.1/gems/rspec-support-3.5.0/lib /Users/gaurish/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.5.4/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb
DEPRECATION WARNING: alias_method_chain is deprecated. Please, use Module#prepend instead. From module, you can access the original method using super. (called from <class:Relation> at /Users/gaurish/code/repo/slavery/lib/slavery/relation.rb:22)
DEPRECATION WARNING: alias_method_chain is deprecated. Please, use Module#prepend instead. From module, you can access the original method using super. (called from <class:Relation> at /Users/gaurish/code/repo/slavery/lib/slavery/relation.rb:23)
DEPRECATION WARNING: alias_method_chain is deprecated. Please, use Module#prepend instead. From module, you can access the original method using super. (called from singleton class at /Users/gaurish/code/repo/slavery/lib/slavery.rb:13)
.F....FFF

Failures:

  1) Slavery returns value from block
     Failure/Error: calculate_without_slavery(operation, column_name, options)

     ArgumentError:
       wrong number of arguments (given 3, expected 2)
     # /Users/gaurish/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/relation/calculations.rb:110:in `calculate'
     # ./lib/slavery/relation.rb:18:in `calculate_with_slavery'
     # /Users/gaurish/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/relation/calculations.rb:40:in `count'
     # /Users/gaurish/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/querying.rb:13:in `count'
     # ./spec/slavery_spec.rb:14:in `block (3 levels) in <top (required)>'
     # ./lib/slavery.rb:41:in `run'
     # ./lib/slavery.rb:35:in `on_master'
     # ./spec/slavery_spec.rb:14:in `block (2 levels) in <top (required)>'

  2) Slavery works with scopes
     Failure/Error: calculate_without_slavery(operation, column_name, options)

     ArgumentError:
       wrong number of arguments (given 3, expected 2)
     # /Users/gaurish/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/relation/calculations.rb:110:in `calculate'
     # ./lib/slavery/relation.rb:18:in `calculate_with_slavery'
     # /Users/gaurish/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/relation/calculations.rb:40:in `count'
     # /Users/gaurish/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/querying.rb:13:in `count'
     # ./spec/slavery_spec.rb:72:in `block (2 levels) in <top (required)>'

  3) Slavery configuration connects to master if slave configuration not specified
     Failure/Error: calculate_without_slavery(operation, column_name, options)

     ArgumentError:
       wrong number of arguments (given 3, expected 2)
     # /Users/gaurish/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/relation/calculations.rb:110:in `calculate'
     # ./lib/slavery/relation.rb:18:in `calculate_with_slavery'
     # /Users/gaurish/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/relation/calculations.rb:40:in `count'
     # /Users/gaurish/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/querying.rb:13:in `count'
     # ./spec/slavery_spec.rb:98:in `block (4 levels) in <top (required)>'
     # ./lib/slavery.rb:41:in `run'
     # ./lib/slavery.rb:31:in `on_slave'
     # ./spec/slavery_spec.rb:98:in `block (3 levels) in <top (required)>'

  4) Slavery configuration raises error when no configuration found
     Failure/Error: expect { Slavery.on_slave { User.count } }.to raise_error(Slavery::Error)

       expected Slavery::Error, got #<ArgumentError: wrong number of arguments (given 3, expected 2)> with backtrace:
         # /Users/gaurish/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/relation/calculations.rb:110:in `calculate'
         # ./lib/slavery/relation.rb:18:in `calculate_with_slavery'
         # /Users/gaurish/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/relation/calculations.rb:40:in `count'
         # /Users/gaurish/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/querying.rb:13:in `count'
         # ./spec/slavery_spec.rb:105:in `block (5 levels) in <top (required)>'
         # ./lib/slavery.rb:41:in `run'
         # ./lib/slavery.rb:31:in `on_slave'
         # ./spec/slavery_spec.rb:105:in `block (4 levels) in <top (required)>'
         # ./spec/slavery_spec.rb:105:in `block (3 levels) in <top (required)>'
     # ./spec/slavery_spec.rb:105:in `block (3 levels) in <top (required)>'

Finished in 0.04407 seconds (files took 0.53068 seconds to load)
9 examples, 4 failures

Failed examples:

rspec ./spec/slavery_spec.rb:13 # Slavery returns value from block
rspec ./spec/slavery_spec.rb:71 # Slavery works with scopes
rspec ./spec/slavery_spec.rb:95 # Slavery configuration connects to master if slave configuration not specified
rspec ./spec/slavery_spec.rb:101 # Slavery configuration raises error when no configuration found
```

**Comment by kenn** [comment]
Fixed with v2.2.0 🎉 🎉
